// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorMegaDesk.Models;

namespace RazorMegaDesk.Migrations
{
    [DbContext(typeof(RazorMegaDeskContext))]
    partial class RazorMegaDeskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorMegaDesk.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Depth");

                    b.Property<string>("DeskMaterial");

                    b.Property<int>("NumberOfDrawers");

                    b.Property<int>("Width");

                    b.HasKey("ID");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("RazorMegaDesk.Models.DeskQuote", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName");

                    b.Property<int>("Depth");

                    b.Property<int?>("DeskID");

                    b.Property<string>("DeskMaterial");

                    b.Property<int>("NumberOfDrawers");

                    b.Property<DateTime>("QuoteDate");

                    b.Property<double>("QuoteTotal");

                    b.Property<int>("RushDays");

                    b.Property<int>("Width");

                    b.HasKey("ID");

                    b.HasIndex("DeskID");

                    b.ToTable("DeskQuote");
                });

            modelBuilder.Entity("RazorMegaDesk.Models.DeskQuote", b =>
                {
                    b.HasOne("RazorMegaDesk.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskID");
                });
#pragma warning restore 612, 618
        }
    }
}
